/*
 * JuliaC jl_options constructor shim.
 *
 * Sets jl_options fields before jl_init via __attribute__((constructor)).
 *
 * Calls jl_parse_opts with a synthetic argv to reuse Julia's own option
 * parsing logic. Saves and restores getopt global state and image_file
 * to avoid interfering with the host process.
 *
 * The argv entries are generated by JuliaC and included via
 * "juliac-jl-options-body.h".
 */

#include <julia.h>
#include <stdlib.h>
#include <getopt.h>

__attribute__((constructor))
static void juliac_set_jl_options(void) {
    /* Save getopt global state */
    int saved_optind = optind;
    int saved_opterr = opterr;
    int saved_optopt = optopt;
    char *saved_optarg = optarg;

    /* Save fields that jl_parse_opts unconditionally overwrites */
    const char *saved_image_file = jl_options.image_file;

    /* Synthetic argv with generated options */
    char *argv[] = {
        "juliac",
#include "juliac-jl-options-body.h"
        NULL
    };
    int argc = (int)(sizeof(argv) / sizeof(argv[0])) - 1; /* exclude NULL */
    char **argvp = argv;

    /* Reset getopt so it parses our argv from the beginning */
    optind = 0;

    jl_parse_opts(&argc, &argvp);

    /* Restore overwritten fields */
    jl_options.image_file = saved_image_file;

    /* Restore getopt global state */
    optind = saved_optind;
    opterr = saved_opterr;
    optopt = saved_optopt;
    optarg = saved_optarg;
}
