/*
 * JuliaC jl_options constructor shim.
 *
 * Sets jl_options fields before jl_init via __attribute__((constructor)).
 *
 * On Unix, we use dladdr/dlsym (like jl_find_dynamic_library_by_addr) to
 * resolve jl_options from our own libjulia dependency rather than a host
 * Julia's copy in the global symbol namespace.
 *
 * On Windows, DLL import resolution is per-module, so &jl_options already
 * resolves to the correct instance from our libjulia dependency.
 *
 * The actual option assignments are generated by JuliaC and included via
 * "juliac-jl-options-body.h".
 */

#include <julia.h>
#include <stdlib.h>

#ifdef _WIN32
#include <windows.h>
#else
#include <dlfcn.h>
#endif

__attribute__((constructor))
static void juliac_set_jl_options(void) {
#ifdef _WIN32
    jl_options_t *opts = &jl_options;
#else
    Dl_info info;
    if (!dladdr((void *)&juliac_set_jl_options, &info)) return;
    void *self = dlopen(info.dli_fname, RTLD_NOLOAD | RTLD_NOW);
    if (!self) return;
    jl_options_t *opts = (jl_options_t *)dlsym(self, "jl_options");
    dlclose(self);
    if (!opts) return;
#endif

    /* Generated option assignments */
#include "juliac-jl-options-body.h"
}
